language: java

jdk:
  - openjdk15
  - openjdk14
  - openjdk13
  - openjdk11
  - openjdk8

services:
  - docker

cache:
  directories:
    - $HOME/.m2

before_install:
  - chmod +x mvnw

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - ./travis/after_success.sh

notifications:
  email: false
